### ISSUE TITLE
Revisit worker architecture

### ISSUE THREAD

**Issue by jo** [eHealthAfrica/kazana-transform#2]
Currently we first query a view with pending docs and transform them in the background and then we substcribe to the changes feed for live transforming.

This has a few disadventages:
- duplicated code in view and filter
- possible race condition when both changes and view return the same doc

I suggest we change that to always use the changes feed and store the last processed update seq in a local doc. I have done this a [plenty of times](https://github.com/jo/couch-daemon) for heavy load workers and it has proven to be solid.
([pouchdb-migrate](https://github.com/eHealthAfrica/pouchdb-migrate) also works like this btw.)

The process is as follows:

1. hash the transformer function
2. use that hash to generate a local id, eg `_local/a653b27246b01cf9204fa9f5dee7cc64`
3. request that checkpoint (local) doc
4. if found, set `since` to the seq from checkpoint doc, else to 0
5. request changes feed from `since`
6. process docs one after other
7. update doc with process status, info and errors when done
8. save seq in checkpoint doc

Also, I'd like to use nano and follow for this instead of PouchDB, because of its enhanced attachment streaming support and the robustness of follow.

**Comment by gr2m** [comment]
Ideally we would share code for the transformation for booth, initial bootstrap and change feed handling. Doing the initial bootstrap from _changes might take much longer than the view, but it could work with the `_local/<id>` workaround. I'm not 100% sure, but I trust that you are, you've done this before, so let's do it :)

Regarding `nano`, I don't mind that at all, we can still change it later if necessary.

**Comment by jo** [comment]
I don't see the checkpoint doc as a workaround, rather as a clean and solid way to keep track of database changes. Just like the replicator, which also uses local checkpoint docs.

**Comment by jo** [comment]
Another argument for changes feed driven bootstrapping is that we don't process deletions otherwise. Because deleted docs do not show up in the view.

**Comment by gr2m** [comment]
> Because deleted docs do not show up in the view

Are you sure, that I can't show deleted documents in views? I can't find any docs on that

**Comment by jo** [comment]
Deleted docs are not emitted in views and there is no switch for that afaik.
